for s in S16R S17R; do \
    dsa \
    -g 2 \
    -f TACnnnnnnAGTnnnnnnCGNNNNNNNNNNNGTCCTCTCT \
    -r CCCnnnnnnnnnACGACAAN \
    --template_dna=AAGAAAGTGGTGTTGGCCAAAAAAGGCGATACCGTGGAGCTGACCTGCACCGCAAGCCAGAAGAAGAACATCCAGTTCCACTGGAAGAACTCCAACCAGATCAAGATCCTGGGCAACCAGGGCAGCTTCTTGACCAAGGGACCTAGCAAGCTGAATGACAGAGTGGACTCTCGGAGGAGCCTGTGGGATCAAGGCAACTTCCCTCTGATCATAAAAAACCTGAAGATAGAGGATAGTGATACCTACATCTGTGAAGTGGAAGATCAGAAGGAGGAAGTGCAGCTGCTGGTGTTCGGGCTGACTGCTAACTCCGATACCCATCTgCTgCAGGGGCAGAGCCTAACACTGACACTGGAGAGCCCTCCTGGCAGCAGCCCAAGCCTGCAaTGCCGCAGCCCtGGAGGCAAGAACATCCAAGGTGGCAAAACCCTTTCTGTCAGCCAGCTGGAACTGCAGGATTCTGGAACCTGGACATGTACAGTGCTGCAGGATCAGAAAACCTTGGAGTTCAAGATTGAT \
    "${s}2.fastq" \
    "${s}1.fastq" \
    > "${s}_dsa_output.csv";
done
